// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcMovie.Data;

#nullable disable

namespace BaithiPTK1062.Migrations
{
    [DbContext(typeof(MvcMovieContext))]
    [Migration("20230629020140_PTKCau3")]
    partial class PTKCau3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("BaithiPTK1062.Models.PTKCau3", b =>
                {
                    b.Property<string>("hovaten")
                        .HasColumnType("TEXT");

                    b.Property<string>("diachi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("sodienthoai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("hovaten");

                    b.ToTable("PTKCau3");
                });
#pragma warning restore 612, 618
        }
    }
}
